### ISSUE TITLE
My maps zip URL is not working

### ISSUE THREAD

**Issue by Jennacidal** [Perytron/ARMA-3-ARTILLERY-CALCULATOR-ARES#10]
Cannot get the map files all I get is this when I click the link in the README

This arma.openlink.bot page can’t be found 
No webpage was found for the web address: 
https://arma.openlink.bot/ares/download/map.zip
HTTP ERROR 404

**Comment by Perytron** [comment]
Hey, @Jennacidal ! I've uploaded the missing files and updated the readme. You can now find them here: https://arma.openlink.bot/assets/map.zip Please

**Comment by Jennacidal** [comment]
> Hey, @Jennacidal ! I've uploaded the missing files and updated the readme. You can now find them here: https://arma.openlink.bot/assets/map.zip

Thanks so much! <3
